### ISSUE TITLE
Impossible to create a project ("New" and "Open" buttons behave the same)

### ISSUE THREAD

**Issue by beckerdenis** [dahuapp/dahu#121]
Normally it should be a "Create" window that appears, with a "create" button, allowing you to put the name of an unexisting directory that will be created.

Instead, a classic "Open directory" window appears, with an "Open" button.
There's no way to specify an unexisting directory. When you try to use "Create folder" and then select this empty folder, it throws an exception (this is an other issue, see #114).

It is related to issue #117 but it was for the version 0.3 and the bug was not the same.
Also similar to issue #97.

**Comment by RdNetwork** [comment]
It turns out that this isn't a bug in itself ; more like an ergonomy problem. The window opened is to select a directory to save the project that will be created (the name is not customizable). You have to select a folder (not 'go into', in which case it simply won't create anything). 

But it is true that this way of doing is counter-intuitive, and should still be treated as an issue.
