### ISSUE TITLE
Context manager function raise Null Pointer

### ISSUE THREAD

**Issue by obzota** [dahuapp/dahu#164]
The function 'setDisableScreencastMenus'  from the file : 
dahu/core/editor/src/main/java/io/dahuapp/editor/kernel/module/ContextManager.java
raises a Null pointer exception when opening a screencast (on both opening a project and creating a new  project).

This appears to happen only on my PC (Mac OS X Yosemite).

**Comment by obzota** [comment]
Under Yosemite, the menu is not in the application but on the system menu. So you can't find the menu through the DOM and the 'lookup' function return 'null'

**Comment by RdNetwork** [comment]
The issue is caused by the fact that on MacOS, the software uses the System menu bar, causing an error because CSS properties of this system bar are not accessible to the application.

A solution would be to disable this aesthetic thingie to let the software be functional.

**Comment by barraq** [comment]
@RdNetwork first it is simple to test if the menu is the system menu menuBar.isUseSystemMenuBar(), second what is causing the bug is the lookup. Indeed it is not possible to do a lookup. However it is, i guess, still possible to disable the menu using setDisable: you only have to avoid doing the lookup.
