### ISSUE TITLE
Error when opening project with the initialize function of object

### ISSUE THREAD

**Issue by benabbon** [dahuapp/dahu#92]
The error come from this line :
 this["is" + this.get("type").charAt(0).toUpperCase() + this.get("type").substring(1)] = function () {
                    return true;
                };
I'll fix it in a patch right away !

**Comment by barraq** [comment]
#92 is not a fix but a workaround which does not fix the real problem.
An object model must always have a type defined. If you have such error it means that some object model is missing a "type" attribute in its defaults attributes.

**Comment by benabbon** [comment]
actually it is a fix, as the problem only occurs when we open old files, and the rewrapping we do in the screencast recalls this function in the correct way !
I forgot to specify that it happened with the old files.

**Comment by barraq** [comment]
Can you point me to the exact line in the Screencast Model where the problem is encountered? Normally if object models are well defined, when we create a new object model with data coming from an old dahu object then it should still be find since new dahu object model have defaults value...

**Comment by benabbon** [comment]
models/screen.js : function : initialize

**Comment by barraq** [comment]
Ok i guess the problem is that in _collections/objects_ we return an _ObjectModel_ as default. This case should never happen... All object must be of know type otherwise must be rejected. ObjectModel is some kind of Abstract class not something that you use directly. We should even remove line 32 and throw an assertion instead.

A good start would be to identify which "old object" causes the object collection to return an ObjectModel. In the meantime I'll give ObjectModel of type: 'unknown'.
